name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: tests
    env:
      SECRET_KEY: DUMMYSECRETVALUEFORTESTS
      UI_SITE_URL: http://example.org
      DATABASE_URL: 'postgis://cykel:cykel@127.0.0.1/cykel'
    steps:
      - uses: actions/checkout@v2
      - uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql password: 'cykel'
          postgresql user: 'cykel'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install geospatial libraries
        run: sudo apt-get install -y libproj-dev libgeos-dev libspatialite-dev libgdal-dev gdal-bin binutils proj-data proj-bin
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run checks
        run: python manage.py check
      - name: Test
        run: pytest -p no:sugar --maxfail=100 tests
